version: '3.10'

services:
  bot:
    image: ghcr.io/wotschofsky/discord-live-translator
    restart: always
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379
      - STT_HOST=http://stt:8000
      - TRANSLATION_HOST=http://libretranslate:5000
    depends_on:
      - stt
      - libretranslate
      - redis

  stt:
    image: ghcr.io/wotschofsky/discord-live-translator/stt
    restart: always

  libretranslate:
    image: libretranslate/libretranslate:v1.3.11
    restart: always
    environment:
      - LT_LOAD_ONLY=de,en,es,fr,it
    stdin_open: true
    tty: true

  redis:
    image: redis:alpine
    command: redis-server
    restart: always
    volumes:
      - redis:/data

volumes:
   redis:
