# Based on https://docs.docker.com/build/ci/github-actions/manage-tags-labels/

name: Build and Publish Docker Image

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  docker:
    name:  Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - id: meta
        name: Docker Meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}},priority=1100
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix=

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Disabled for reasons discussed in https://github.com/docker/build-push-action/issues/820
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
